

configfile: os.path.join(workflow.basedir, '../', 'config', 'config.yaml')


include: os.path.join("rules", "preflight.smk")
include: os.path.join("rules", "megapharokka.smk")


# Mark target rules
target_rules = []
def targetRule(fn):
    assert fn.__name__.startswith('__')
    target_rules.append(fn.__name__[2:])
    return fn


@targetRule
rule all:
    input:
        targets


@targetRule
rule print_targets:
    run:
        print("\nTop level rules are: \n", file=sys.stderr)
        print("* " + "\n* ".join(target_rules) + "\n\n", file=sys.stderr)
