args:
    input:
    output: 'pharokkagobrrrt.out/'
    log: 'pharokkagobrrrt/pharokkagobrrrt.log'
megapharokka:
    -g prodigal-gv
    --sensitivity 2
    --skip_extra_annotations
    --skip_mash
    --mmseqs2
resources:
    big:
        cpu: 64
        mem: 64000
        time: "01:00:00"
    sml:
        cpu: 1
        mem: 2000
        time: "00:10:00"
